// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM1tGX4te-I0Sd71v7kjc8dS-B1oOgoF8',
    appId: '1:1082862756676:web:bbc88a6f74f5be4be12d11',
    messagingSenderId: '1082862756676',
    projectId: 'wild-cards-ac1cf',
    authDomain: 'wild-cards-ac1cf.firebaseapp.com',
    storageBucket: 'wild-cards-ac1cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfZriZjsI43CAILM9Ev-HaqMSFlR-iwP0',
    appId: '1:1082862756676:android:917d20a06d5e938ee12d11',
    messagingSenderId: '1082862756676',
    projectId: 'wild-cards-ac1cf',
    storageBucket: 'wild-cards-ac1cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGmB35FfdmQh_Y80MOR_c9kJyVUgHr3ys',
    appId: '1:1082862756676:ios:ec2fbce3f80773d1e12d11',
    messagingSenderId: '1082862756676',
    projectId: 'wild-cards-ac1cf',
    storageBucket: 'wild-cards-ac1cf.appspot.com',
    iosBundleId: 'com.example.iShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGmB35FfdmQh_Y80MOR_c9kJyVUgHr3ys',
    appId: '1:1082862756676:ios:f0aa4296e9c79ae8e12d11',
    messagingSenderId: '1082862756676',
    projectId: 'wild-cards-ac1cf',
    storageBucket: 'wild-cards-ac1cf.appspot.com',
    iosBundleId: 'com.example.iShop.RunnerTests',
  );
}
